- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Lazygit
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - fzf
    - fd
    - bat

- name: Setup fish shell ppa (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "ppa:fish-shell/release-4"
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

# - name: Add Fish repo to APT sources list
#   ansible.builtin.copy:
#     dest: /etc/apt/sources.list.d/shells:fish:release:4.list
#     content: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_12/ /"
#   when: ansible_facts['distribution'] == 'Debian'
#
# - name: Add GPG key for Fish repo
#   ansible.builtin.get_url:
#     url: https://download.opensuse.org/repositories/shells:fish:release:4/Debian_12/Release.key
#     dest: /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg
#     mode: '0644'
#   when: ansible_facts['distribution'] == 'Debian'
#
# - name: Convert GPG key to dearmored format
#   ansible.builtin.command: gpg --dearmor -o /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg
#   args:
#     creates: /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg
#   when: ansible_facts['distribution'] == 'Debian'

- name: Install fish shell
  ansible.builtin.apt:
    name: fish
    state: present

- name: Setup default shell
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: /usr/bin/fish

- name: Setup config dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

# - name: Install fish config
#   ansible.builtin.copy:
#     src: "fish"
#     dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
#     owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
#     group: "{{ lookup('ansible.builtin.env', 'USER') }}"
#     mode: '0755'

- name: Install configs
  ansible.posix.synchronize:
    src: "fish"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    recursive: true
    delete: true

- name: Copy hidden config
  ansible.builtin.template:
    src: conf.d/bitwarden.fish.j2
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/fish/conf.d/bitwarden.fish"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'

