- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Setup fish shell ppa
  ansible.builtin.apt_repository:
    repo: "ppa:fish-shell/release-4"
    state: present

- name: Install fish shell
  ansible.builtin.apt:
    name: fish
    state: present

- name: Setup default shell
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: /usr/bin/fish

- name: Install fish config
  ansible.builtin.copy:
    src: "fish"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0755'

- name: Copy config
  ansible.builtin.template:
    src: conf.d/bitwarden.fish.j2
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/fish/conf.d/bitwarden.fish"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'
