- name: Update Apt
  become: true
  when: ansible_os_family != "Darwin"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    autoremove: true
    autoclean: true
