- name: Setup config dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    # group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Install Config
  ansible.builtin.copy:
    src: ".ssh"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    # group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'
