- name: Setup Kubectl Dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Copy Kubectl Config
  ansible.builtin.copy:
    src: "k3s.yaml"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/k3s.yaml"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'

- name: Install Kubectl
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    state: "{{ item.state }}"
  with_items:
    - { name: kubectl, classic: true, state: present }
    - { name: helm, classic: true, state: present }

- name: Install Brew Packages
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: false
  with_items:
    - { name: k9s, state: present }
    - { name: kubeseal, state: present }

- name: Check if flux is installed
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/flux"
  register: flux_stat

- name: Install flux cd
  ansible.builtin.shell: |
    curl -s https://fluxcd.io/install.sh | FLUX_VERSION=2.0.0 bash -s ~/.local/bin
  register: flux_install
  changed_when: flux_install.stdout != ''
  when: not flux_stat.stat.exists
