- name: Setup Kubectl Dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Copy Kubectl Config
  ansible.builtin.copy:
    src: "k3s.yaml"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/k3s.yaml"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'

- name: Install Kubectl
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    state: "{{ item.state }}"
  with_items:
    - { name: kubectl, classic: true, state: present }
    - { name: helm, classic: true, state: present }

- name: Install Brew Packages
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: false
  with_items:
    - { name: k9s, state: present }
    - { name: kubeseal, state: present }
    - { name: talosctl, state: present }
    - { name: fluxcd/tap/flux, state: present }
