- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Copy gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.gitconfig"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'
