- name: Install Dependencies
  ansible.builtin.apt:
    name: pipx
    state: present

- name: Install Ansible
  community.general.pipx:
    name: "{{ item }}"
  with_items:
    - "ansible"
    - "ansible-lint"
