- name: Setup Development Environment
  hosts: local-machines
  # hosts: dev-debian
  # become: true
  vars:
    gui: false
  roles:
    - apt-update
    - setup-snap
    - setup-flatpak
    - setup-homebrew
    - rust
    - python3
    - git
    - zsh
    - ssh
    - tmux
    - bw
    - aichat
    - ansible
    - kubectl
    # - nvim
    # - role: node
    #   vars:
    #     node_version: "20.19.0"
    - docker
    - dotconfig
    - role: gui-apps
      when: gui
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: |
          user: {{ lookup('ansible.builtin.env', 'USER') }} \n
          home: {{ lookup('ansible.builtin.env', 'HOME') }}
