- name: Setup Development Environment
  hosts: local-machines
  # hosts: dev-debian
  # become: true
  vars:
    gui: false
    is_linux: "{{ ansible_os_family != 'Darwin' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
  roles:
    - role: apt-update
      when: is_linux
    - role: setup-snap
      when: is_linux
    - role: setup-flatpak
      when: is_linux
    # - setup-homebrew
    - role: rust
    - role: python3
    - role: git
      when: is_linux
    - role: opencode
    - role: zsh
    - role: ssh
    - role: tmux
    - role: bw
    - role: aichat
    - role: nvim
    # # - ansible
    - role: kubectl
    - role: docker
      when: is_linux
    # - dotconfig
    - role: gui-apps
      when: gui
    - role: stow
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: |
          user: {{ lookup('ansible.builtin.env', 'USER') }} \n
          home: {{ lookup('ansible.builtin.env', 'HOME') }} \n
          platform: {{ ansible_os_family }}
