- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - btm
    - ripgrep
    - gdu

- name: Install Lazygit
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - lazygit
    - neovim

- name: Setup config dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Install Nvim Config
  ansible.builtin.copy:
    src: "nvim"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'
