- name: Install Dependencies (Snap)
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  with_items:
    - { name: nvim, classic: true }

- name: Install Dependencies (APT)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - make
    - pip
    - python3
    - ripgrep
    - luarocks
    - lua5.1
    - liblua5.1-0-dev
    - xclip
    - wl-clipboard

- name: Install Dependencies (Homebrew)
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - lazygit

- name: Setup config dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Install Nvim Config
  ansible.builtin.copy:
    src: "nvim"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0755'

# - name: Install Nvim Config
#   ansible.posix.synchronize:
#     src: "nvim"
#     dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
#     recursive: true
#     delete: true
